/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab7_jamilgarcia;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author JamilGarcía
 */
public class Principal extends javax.swing.JFrame {

    
    public Principal() {
        initComponents();
        Login.setVisible(true);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_login_Usuario = new javax.swing.JTextField();
        tf_login_Contraseña = new javax.swing.JTextField();
        b_login_Login = new javax.swing.JButton();
        b_login_crearCuenta = new javax.swing.JButton();
        CrearCuenta = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_crearCuenta_usuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_crearCuenta_contraseña = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_crearCuenta_edad = new javax.swing.JFormattedTextField();
        b_crearCuenta_CrearCuenta = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tf_crearCuenta_Nombre = new javax.swing.JTextField();
        Admin = new javax.swing.JFrame();
        jLabel9 = new javax.swing.JLabel();

        Login.setMinimumSize(new java.awt.Dimension(604, 553));

        jLabel1.setText("Login");

        jLabel2.setText("Usuario: ");

        jLabel3.setText("Password: ");

        b_login_Login.setText("Login");
        b_login_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_login_LoginMouseClicked(evt);
            }
        });

        b_login_crearCuenta.setText("Crear Cuenta");
        b_login_crearCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_login_crearCuentaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login.getContentPane());
        Login.getContentPane().setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(38, 38, 38)
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_login_Usuario)
                            .addComponent(tf_login_Contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)))
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(b_login_Login))
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLabel1))
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(b_login_crearCuenta)))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_login_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tf_login_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(b_login_Login)
                .addGap(43, 43, 43)
                .addComponent(b_login_crearCuenta)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        CrearCuenta.setMinimumSize(new java.awt.Dimension(446, 406));

        jLabel4.setText("Crear Cuenta");

        jLabel5.setText("Usuario:");

        jLabel6.setText("Contraseña:");

        jLabel7.setText("Edad:");

        tf_crearCuenta_edad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##"))));

        b_crearCuenta_CrearCuenta.setText("Crear Cuenta");
        b_crearCuenta_CrearCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_crearCuenta_CrearCuentaMouseClicked(evt);
            }
        });

        jLabel8.setText("Nombre:");

        javax.swing.GroupLayout CrearCuentaLayout = new javax.swing.GroupLayout(CrearCuenta.getContentPane());
        CrearCuenta.getContentPane().setLayout(CrearCuentaLayout);
        CrearCuentaLayout.setHorizontalGroup(
            CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearCuentaLayout.createSequentialGroup()
                .addGroup(CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CrearCuentaLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(CrearCuentaLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(33, 33, 33)
                                .addComponent(tf_crearCuenta_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CrearCuentaLayout.createSequentialGroup()
                                .addGroup(CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_crearCuenta_contraseña)
                                    .addComponent(tf_crearCuenta_edad)
                                    .addComponent(tf_crearCuenta_Nombre)))))
                    .addGroup(CrearCuentaLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel4))
                    .addGroup(CrearCuentaLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(b_crearCuenta_CrearCuenta)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        CrearCuentaLayout.setVerticalGroup(
            CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearCuentaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addGap(31, 31, 31)
                .addGroup(CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_crearCuenta_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_crearCuenta_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_crearCuenta_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_crearCuenta_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(b_crearCuenta_CrearCuenta)
                .addGap(63, 63, 63))
        );

        Admin.setMinimumSize(new java.awt.Dimension(400, 300));

        jLabel9.setText("Funciona");

        javax.swing.GroupLayout AdminLayout = new javax.swing.GroupLayout(Admin.getContentPane());
        Admin.getContentPane().setLayout(AdminLayout);
        AdminLayout.setHorizontalGroup(
            AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel9)
                .addContainerGap(288, Short.MAX_VALUE))
        );
        AdminLayout.setVerticalGroup(
            AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel9)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 946, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_login_crearCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_login_crearCuentaMouseClicked
        // TODO add your handling code here:
        CrearCuenta.setVisible(true);
        
    }//GEN-LAST:event_b_login_crearCuentaMouseClicked

    private void b_crearCuenta_CrearCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_crearCuenta_CrearCuentaMouseClicked
        // TODO add your handling code here:
        Usuarios usuario = new Usuarios(tf_crearCuenta_usuario.getText(), 
                tf_crearCuenta_contraseña.getText(), 
                tf_crearCuenta_Nombre.getText(), 
                Integer.parseInt(tf_crearCuenta_edad.getText()));
        AdminUsuarios adUs = new AdminUsuarios("./usuarios.jg");
        adUs.cargarArchivo();
        adUs.setUsuario(usuario);
        adUs.escribirArchivo();
        JOptionPane.showMessageDialog(this, "Guardado con exito");
        tf_crearCuenta_Nombre.setText("");
        tf_crearCuenta_contraseña.setText("");
        tf_crearCuenta_edad.setText("");
        tf_crearCuenta_usuario.setText("");
        CrearCuenta.setVisible(false);
    }//GEN-LAST:event_b_crearCuenta_CrearCuentaMouseClicked

    private void b_login_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_login_LoginMouseClicked
        // TODO add your handling code here:
        AdminUsuarios adUs = new AdminUsuarios("./usuarios.jg");
        adUs.cargarArchivo();
        ArrayList <Usuarios> Lusu = new ArrayList();
        Lusu = adUs.getUsua();
        for (int i = 0; i < Lusu.size(); i++) {
            if (tf_login_Usuario.getText().equals("leobanegas")){
                if (tf_login_Contraseña.getText().equals("99")) {
                    Admin.setVisible(true);
                    Login.setVisible(false);
                }
            } else if (tf_login_Usuario.getText().equals(Lusu.get(i).getUsuario())){
                if (tf_login_Contraseña.getText().equals(Lusu.get(i).getContraseña())){
                    new Principal().setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_b_login_LoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Admin;
    private javax.swing.JFrame CrearCuenta;
    private javax.swing.JFrame Login;
    private javax.swing.JButton b_crearCuenta_CrearCuenta;
    private javax.swing.JButton b_login_Login;
    private javax.swing.JButton b_login_crearCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tf_crearCuenta_Nombre;
    private javax.swing.JTextField tf_crearCuenta_contraseña;
    private javax.swing.JFormattedTextField tf_crearCuenta_edad;
    private javax.swing.JTextField tf_crearCuenta_usuario;
    private javax.swing.JTextField tf_login_Contraseña;
    private javax.swing.JTextField tf_login_Usuario;
    // End of variables declaration//GEN-END:variables
}
